pluginManagement {
	repositories {
		mavenLocal()
		if (System.getenv("GITHUB_ACTIONS") != "true" || System.getenv("FNT_RUNNER") == "true") {
			maven { url = uri("${artifactoryContextUrl}/plugins-gradle-org") }
			maven { url = uri("${artifactoryContextUrl}/plugins-gradle-org-cache") }
			maven { url = uri("${artifactoryContextUrl}/maven.central") }
		} else {
			mavenCentral()
			gradlePluginPortal()
		}
	}
}
rootProject.name = 'jdbcTest'
