name: Build

on:
  push:
    # trigger after PR merge
    branches: ["main"]
    # trigger on tag push
    tags: ["[0-9]+.[0-9]+.[0-9]+"]
  # trigger for PRs
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["main"]
  # manual trigger
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
env:
  GIT_CHECKOUT_REF: "${{ github.event_name != 'pull_request' && github.ref || github.event.pull_request.head.sha }}"
  JAVA_VERSION: 25
  GENERATE_GRADLE_JOB_SUMMARY: never

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.1
        ports:
          - 22222:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ env.GIT_CHECKOUT_REF }}
          persist-credentials: false

      - name: Setup java
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0 # zizmor: ignore[cache-poisoning]
        with:
          add-job-summary: ${{ env.GENERATE_GRADLE_JOB_SUMMARY }}
          cache-disabled: false
          cache-read-only: ${{ github.event_name == 'pull_request' }}

      - name: Set version
        if: ${{ github.ref_type == 'tag' }}
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Check code format
        run: ./gradlew spotlessCheck

      - name: Build
        run: ./gradlew build -Pversion=${{ github.ref_name }}

      - name: Test
        run: ./gradlew testJar -Pversion=${{ github.ref_name }}

      - name: Create GitHub release
        if: ${{ github.ref_type == 'tag' }}
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3 # zizmor: ignore[superfluous-actions]
        with:
          name: "JDBC Check ${{ github.ref_name }}"
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./build/libs/*.jar
